name: OWASP ZAP Security Scan

on: [push]

jobs:
    check-run:
      runs-on: ubuntu-latest
  
      steps:
  
      - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx
  
      - name: ZAP Scan
        uses: ./
        id: action-full-scan
        with:
          target: 'http://localhost'
          allow_issue_writing: false