name: StackHawk Actions

on:
  push:
    branches: [ "main" ]

jobs:
  stackhawk-hawkscan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo!
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services with Docker Compose
        run: |
          # Create a simple Docker Compose file
          echo "version: '3'
          services:
            myapp:
              build:
                context: ./VMs
                dockerfile: Dockerfile
              ports:
                - '8080:8080'
            nginx:
              image: nginx
              ports:
                - '8080:80'
              volumes:
                - ./nginx.conf:/etc/nginx/conf.d/default.conf
              depends_on:
                - myapp
          " > docker-compose.yml

          # Start the services
          docker-compose up -d

      - name: Wait for the application to start
        run: |
          echo "Waiting for the application to fully start..."
          sleep 60  # Adjust based on your application's startup time

      - name: Verify services are running
        run: docker-compose ps

      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: hawk.0NqxByCIfHvHe2itsjI5.WUai04MsNoCohWBqNvrW  # Use GitHub secrets for sensitive data
          # Specify the base URL for HawkScan to target
          #configurationFiles: stackhawk.yml
    
      - name: Tear down the services
        if: always()  # Ensure this runs even if previous steps fail
        run: docker-compose down


          