name: StackHawk Actions
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the job of running the Javaspringvulny application and then running HawkScan to test it
  stackhawk-hawkscan:
    # This is the OS we chose to run the project on
    runs-on: ubuntu-latest
    # These are the sequential steps for running the action
    steps:
      # First, the action checks out the repo to get the latest version
      - name: Check out Repo!
        uses: actions/checkout@v2
      # Next, the action builds and runs the Javaspringvulny application in a Docker container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image and run container
        run: |
          cd VMs  
          chmod +x buildDockerImage.sh 
          ./buildDockerImage.sh  
          docker network create hawk-network || true  
          docker run -d --name your-app-container-name --network hawk-network -p 8443:8443 benchmark &  
      - name: Check running containers
        run: docker ps

      - name: Wait for the application to start
        run: sleep 60  

      - name: HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: hawk.V1tQcRl8ysFwWSuBIiET.c7gliJIbsEa6aFefDU9Y
          configurationFiles: stackhawk.yml 
          host: http://$(steps.get_ip.outputs.container_ip):8443
      #- name: Run HawkScan
        #uses: stackhawk/hawkscan-action@v2

       # with:
       #   targetUrl: http://localhost:8443  # Или используйте IP-адрес вашего хоста
        #  apiKey: hawk.V1tQcRl8ysFwWSuBIiET.c7gliJIbsEa6aFefDU9Y
        #  configurationFiles: stackhawk.yml 
          