name: StackHawk Actions
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the job of running the Javaspringvulny application and then running HawkScan to test it
  stackhawk-hawkscan:
    # This is the OS we chose to run the project on
    runs-on: ubuntu-latest
    # These are the sequential steps for running the action
    steps:
      - name: Check out Repo!
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Build and run your service
        run: |
          cd VMs  # Папка с вашим Dockerfile или кодом приложения
          docker build -t benchmark .  # Соберите ваш образ приложения
          docker-compose up -d



      - name: HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: hawk.V1tQcRl8ysFwWSuBIiET.c7gliJIbsEa6aFefDU9Y
          configurationFiles: stackhawk.yml
          
    
          