name: StackHawk Actions
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the job of running the Javaspringvulny application and then running HawkScan to test it
  stackhawk-hawkscan:
    # This is the OS we chose to run the project on
    runs-on: ubuntu-latest
    # These are the sequential steps for running the action
    steps:
      # First, the action checks out the repo to get the latest version
      - name: Check out Repo!
        uses: actions/checkout@v2
      # Next, the action builds and runs the Javaspringvulny application in a Docker container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image and run container
        run: |
          cd VMs  
          chmod +x buildDockerImage.sh 
          ./buildDockerImage.sh  
          docker network create hawk-network || true  
          docker run -d --name your-app-container-name --network hawk-network -p 8443:8443 benchmark &  

      - name: Check running containers
        run: docker ps

      - name: Wait for the application to start
        run: sleep 30  

      - name: Get container IP address
        id: get_ip
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' your-app-container-name)
          echo "Container IP is $CONTAINER_IP"
          echo "::set-output name=container_ip::$CONTAINER_IP"

      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: hawk.V1tQcRl8ysFwWSuBIiET.c7gliJIbsEa6aFefDU9Y
          targetUrl: http://${{ steps.get_ip.outputs.container_ip }}:8443
          configurationFiles: stackhawk.yml 
